---
json_rpc_url: https://api.devnet.solana.com
websocket_url: 'wss://api.devnet.solana.com/'
keypair_path: /root/solana-file-wallet/file-wallet.json
address_labels:
  '11111111111111111111111111111111': System Program
commitment: confirmed
